apiVersion: v1
kind: Template
metadata: {}
parameters:
- name: WEBHOOK_NAME
  required: true
  description: Name of the webhook (defaults to enforceenv).
  value: enforceenv
- name: WEBHOOK_NAMESPACE
  required: true
  description: Name of the project where the webhook is being deployed.
- name: WEBHOOK_CA_BUNDLE
  required: true
  description: Content of /etc/origin/master/service-signer.crt base64 encoded or the CA which signed the certificate used in the webhook.
objects:
- apiVersion: admissionregistration.k8s.io/v1beta1
  kind: MutatingWebhookConfiguration
  metadata:
    labels:
      webhook: ${WEBHOOK_NAME}
    name: ${WEBHOOK_NAME}
  webhooks:
  - name: ${WEBHOOK_NAME}.admission.online.openshift.io
    rules:
    - operations:
      - CREATE
      apiGroups:
      - "*"
      apiVersions:
      - "*"
      resources:
      - pods
    clientConfig:
      url: https://${WEBHOOK_NAME}.${WEBHOOK_NAMESPACE}.svc
      path: /
      caBundle: ${WEBHOOK_CA_BUNDLE}
